# Exported from Render on 2025-02-25T14:32:02Z
services:
- type: web
  name: n8n
  runtime: node
  repo: https://github.com/serkanayaz/n8n
  plan: free
  envVars:
  - key: NODE_OPTIONS
    sync: false
  - key: NODE_OPTIONS
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: WEBHOOK_TUNNEL_URL
    sync: false
  - key: NODE_VERSION
    sync: false
  - key: N8N_RUNNERS_ENABLED
    sync: false
  - key: N8N_PROTOCOL
    sync: false
  - key: N8N_PORT
    sync: false
  - key: N8N_HOST
    sync: false
  - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
    sync: false
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: N8N_EDITOR_BASE_URL
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  - key: ENABLE_ALPINE_PRIVATE_NETWORKING
    sync: false
  - key: DB_TYPE
    sync: false
  - key: DB_POSTGRESDB_USER
    sync: false
  - key: DB_POSTGRESDB_PORT
    sync: false
  - key: DB_POSTGRESDB_PASSWORD
    sync: false
  - key: DB_POSTGRESDB_HOST
    sync: false
  - key: DB_POSTGRESDB_DATABASE
    sync: false
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: ENABLE_ALPINE_PRIVATE_NETWORKING
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  - key: DB_POSTGRESDB_PASSWORD
    sync: false
  - key: DB_POSTGRESDB_USER
    sync: false
  - key: DB_POSTGRESDB_DATABASE
    sync: false
  - key: DB_POSTGRESDB_PORT
    sync: false
  - key: DB_POSTGRESDB_HOST
    sync: false
  - key: DB_TYPE
    sync: false
  - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
    sync: false
  - key: N8N_RUNNERS_ENABLED
    sync: false
  - key: NODE_VERSION
    sync: false
  - key: N8N_PORT
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: WEBHOOK_TUNNEL_URL
    sync: false
  - key: N8N_PROTOCOL
    sync: false
  - key: N8N_HOST
    sync: false
  - key: N8N_EDITOR_BASE_URL
    sync: false
  region: frankfurt
  buildCommand: pnpm install --frozen-lockfile; pnpm run build
  startCommand: pnpm run start
version: "1"
